services:
  controller:
    image: alpine:latest
    container_name: controller

    networks:
      main:
        ipv4_address: 192.168.200.10

    volumes:
      - ./resolv.conf:/etc/resolv.conf 

    command: /bin/sh
    stdin_open: true
    tty: true

  dns_lab:
    image: internetsystemsconsortium/bind9:9.18
    container_name: dns_lab
    volumes:
      - ./lab/named.conf:/etc/bind/named.conf
      - ./lab/zones:/etc/bind/zones
    platform: linux/x86_64
    networks:
      main:
        ipv4_address: 192.168.200.100

  dns_lab_happy:
    image: internetsystemsconsortium/bind9:9.18
    container_name: dns_lab_happy
    volumes:
      - ./happy.lab/named.conf:/etc/bind/named.conf
      - ./happy.lab/zones:/etc/bind/zones
    platform: linux/x86_64
    networks:
      main:
        ipv4_address: 192.168.200.101

  dovecot:
    image: dovecot/dovecot
    container_name: mail
    networks:
      - main

    # ports:
    #   - "25:25"   # SMTPポート
    #   - "143:143" # IMAPポート
    # environment:
    #   - ENABLE_SPAMASSASSIN=0
    #   - ENABLE_CLAMAV=0
    #   - ENABLE_FAIL2BAN=0
    #   - ONE_DIR=1
    #   - DMS_DEBUG=0
    platform: linux/x86_64
    # restart: unless-stopped

networks:
  main:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
